/* eslint-disable */
import type { Dictionary } from './en';

const es = {
  common: { appName: 'Guía Alemania', loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', back: 'Atrás', next: 'Siguiente', submit: 'Enviar', yes: 'Sí', no: 'No', or: 'o', error: 'Error', success: 'Éxito', close: 'Cerrar', optional: 'Opcional', required: 'Requerido', search: 'Buscar', noResults: 'No se encontraron resultados', confirm: 'Confirmar', welcome: 'Bienvenido' },
  landing: { hero: 'Tu guía completa para vivir en Alemania', subtitle: 'Navega la burocracia, gestiona documentos y rastrea plazos — todo en un solo lugar.', getStarted: 'Comenzar', login: 'Iniciar sesión', features: 'Características', featureFlows: 'Procesos paso a paso', featureFlowsDesc: 'Sigue procesos guiados para solicitudes de visa, registro y más.', featureDocs: 'Bóveda de documentos', featureDocsDesc: 'Almacena y rastrea todos tus documentos importantes con alertas de vencimiento.', featureDeadlines: 'Rastreador de plazos', featureDeadlinesDesc: 'Nunca pierdas una cita o fecha de renovación.', featureI18n: 'Soporte multilingüe', featureI18nDesc: 'Disponible en 11 idiomas incluyendo árabe, turco, ucraniano y más.', pricing: 'Precios', pricingSubtitle: 'Elige el plan que te convenga', free: 'Gratis', premium: 'Premium', premiumPrice: '€4,99/mes', premiumYearly: '€39,99/año', saveYearly: 'Ahorra 33%', currentPlan: 'Plan actual', upgrade: 'Actualizar ahora', freeTier1: 'Hasta 3 procesos activos', freeTier2: 'Hasta 10 documentos', freeTier3: 'Rastreo básico de plazos', freeTier4: 'Soporte comunitario', premiumTier1: 'Procesos ilimitados', premiumTier2: 'Documentos ilimitados', premiumTier3: 'Soporte prioritario por email', premiumTier4: 'Experiencia sin anuncios', premiumTier5: 'Exportar documentos como PDF', premiumTier6: 'Recordatorios avanzados', premiumTier7: 'Lista de verificación personalizada' },
  auth: { login: 'Iniciar sesión', register: 'Crear cuenta', email: 'Correo electrónico', password: 'Contraseña', confirmPassword: 'Confirmar contraseña', forgotPassword: '¿Olvidaste tu contraseña?', noAccount: '¿No tienes cuenta?', hasAccount: '¿Ya tienes cuenta?', loginError: 'Correo o contraseña inválidos', registerError: 'Error en el registro. Inténtalo de nuevo.', passwordMismatch: 'Las contraseñas no coinciden', checkEmail: 'Revisa tu correo para confirmar tu cuenta', fullName: 'Nombre completo', logout: 'Cerrar sesión' },
  onboarding: { title: 'Configuremos tu perfil', subtitle: 'Esto nos ayuda a personalizar tu experiencia', step1Title: 'Tipo de visa', step1Desc: '¿Qué tipo de visa tienes o estás solicitando?', step2Title: 'Detalles de solicitud', step2Desc: 'Cuéntanos más sobre tu situación', step3Title: 'Ubicación', step3Desc: '¿Dónde estás en Alemania?', visaType: 'Tipo de visa', applicationType: '¿Es tu primera solicitud o una renovación?', firstApplication: 'Primera solicitud', renewal: 'Renovación', city: 'Ciudad', zipCode: 'Código postal', visaExpiry: 'Fecha de vencimiento del visa', complete: 'Completar configuración', step: 'Paso', of: 'de' },
  dashboard: { title: 'Panel de control', welcomeBack: 'Bienvenido de vuelta', yourFlows: 'Tus procesos', yourDocuments: 'Tus documentos', upcomingDeadlines: 'Plazos próximos', quickActions: 'Acciones rápidas', startNewFlow: 'Nuevo proceso', addDocument: 'Agregar documento', viewAllFlows: 'Ver todos los procesos', viewAllDocs: 'Ver todos los documentos', viewAllDeadlines: 'Ver todos los plazos', noFlows: 'Sin procesos activos', noDocs: 'Sin documentos', noDeadlines: 'Sin plazos próximos', progress: 'Progreso', dueIn: 'En', days: 'días', overdue: 'Vencido', today: 'Hoy', premiumBanner: 'Actualizar a Premium', premiumBannerDesc: 'Procesos ilimitados, sin anuncios y más.', premiumBannerCta: 'Saber más' },
  flows: { title: 'Procesos', subtitle: 'Guías paso a paso para tu tipo de visa', startFlow: 'Iniciar', continueFlow: 'Continuar', completed: 'Completado', inProgress: 'En progreso', notStarted: 'No iniciado', steps: 'Pasos', step: 'Paso', markDone: 'Marcar como hecho', markUndone: 'Marcar como no hecho', notes: 'Notas', addNote: 'Agregar nota...', saveNote: 'Guardar nota', requiredDocs: 'Documentos requeridos', usefulLinks: 'Enlaces útiles', tips: 'Consejos', optional: 'Paso opcional', flowProgress: 'Progreso del proceso', noFlows: 'No hay procesos disponibles para tu tipo de visa', backToFlows: 'Volver a procesos', limitReached: 'Límite del plan gratuito alcanzado', limitReachedDesc: 'Actualiza a Premium para procesos ilimitados.' },
  docs: { title: 'Documentos', subtitle: 'Rastrea todos tus documentos importantes', addDocument: 'Agregar documento', editDocument: 'Editar documento', docType: 'Tipo de documento', docName: 'Nombre del documento', issueDate: 'Fecha de emisión', expiryDate: 'Fecha de vencimiento', status: 'Estado', notes: 'Notas', linkedFlow: 'Proceso vinculado', noDocuments: 'Sin documentos agregados', valid: 'Válido', pending: 'Pendiente', expired: 'Vencido', notUploaded: 'No subido', deleteConfirm: '¿Estás seguro de que quieres eliminar este documento?', limitReached: 'Límite del plan gratuito alcanzado', limitReachedDesc: 'Actualiza a Premium para documentos ilimitados.' },
  deadlines: { title: 'Plazos', subtitle: 'Nunca pierdas una fecha importante', addDeadline: 'Agregar plazo', editDeadline: 'Editar plazo', deadlineTitle: 'Título', description: 'Descripción', dueDate: 'Fecha límite', remindAt: 'Recordatorio', markDone: 'Marcar como hecho', markUndone: 'Marcar como no hecho', done: 'Hecho', upcoming: 'Próximo', overdue: 'Vencido', noDeadlines: 'Sin plazos establecidos', deleteConfirm: '¿Estás seguro de que quieres eliminar este plazo?' },
  nav: { dashboard: 'Panel', flows: 'Procesos', documents: 'Documentos', deadlines: 'Plazos', settings: 'Configuración', logout: 'Cerrar sesión', language: 'Idioma', premium: 'Premium', upgrade: 'Actualizar' },
  visa: { student_visa: 'Visa de estudiante', job_seeker_visa: 'Visa de búsqueda de empleo', blue_card: 'Tarjeta azul', work_permit: 'Permiso de trabajo', family_reunion: 'Reunificación familiar', freelance_visa: 'Visa de freelance', permanent_residence: 'Residencia permanente', other: 'Otro' },
  premium: { title: 'Actualizar a Premium', subtitle: 'Desbloquea todo el poder de Guía Alemania', monthly: 'Mensual', yearly: 'Anual', monthlyPrice: '€4,99/mes', yearlyPrice: '€39,99/año', savePercent: 'Ahorra 33%', subscribe: 'Suscribirse', manage: 'Gestionar suscripción', cancel: 'Cancelar suscripción', cancelConfirm: '¿Estás seguro de que quieres cancelar tu suscripción?', active: 'Activa', cancelled: 'Cancelada', expired: 'Expirada', renewsOn: 'Se renueva el', expiresOn: 'Expira el', feature1: 'Procesos y documentos ilimitados', feature2: 'Sin anuncios', feature3: 'Soporte prioritario', feature4: 'Exportar PDF', feature5: 'Recordatorios avanzados (SMS y Email)', feature6: 'Listas personalizadas', thankYou: '¡Gracias por suscribirte!', welcomePremium: 'Bienvenido a Premium.', paymentSuccess: 'Pago exitoso', paymentCancelled: 'Pago cancelado', returnToDashboard: 'Volver al panel', processing: 'Procesando tu pago...', error: 'Algo salió mal. Inténtalo de nuevo.' },
  affiliates: { recommended: 'Servicios recomendados', subtitle: 'Socios de confianza para ayudarte a establecerte en Alemania', banking: 'Banca', insurance: 'Seguro médico', mobile: 'Planes móviles', housing: 'Vivienda', learn: 'Saber más', disclaimer: 'Podemos recibir una comisión cuando te registras a través de nuestros enlaces. Esto no afecta el precio.', openAccount: 'Abrir cuenta', getQuote: 'Obtener cotización', viewPlans: 'Ver planes', findHousing: 'Buscar vivienda' },
  support: { tipTitle: 'Apoya este proyecto', tipSubtitle: 'Ayúdanos a mantener esta guía gratuita y actualizada', tipAmount: 'Elige un monto', tipCustom: 'Monto personalizado', tipSend: 'Enviar propina', tipThankYou: '¡Gracias por tu apoyo!', tipOneTime: 'Propina única' },
  ads: { sponsored: 'Patrocinado', advertisement: 'Publicidad' },
};

export default es as unknown as Dictionary;