/* eslint-disable */
import type { Dictionary } from './en';

const fr = {
  common: { appName: 'Guide Allemagne', loading: 'Chargement...', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', back: 'Retour', next: 'Suivant', submit: 'Soumettre', yes: 'Oui', no: 'Non', or: 'ou', error: 'Erreur', success: 'Succès', close: 'Fermer', optional: 'Optionnel', required: 'Requis', search: 'Rechercher', noResults: 'Aucun résultat trouvé', confirm: 'Confirmer', welcome: 'Bienvenue' },
  landing: { hero: 'Votre guide complet pour vivre en Allemagne', subtitle: 'Naviguez la bureaucratie, gérez vos documents et suivez vos échéances — tout en un seul endroit.', getStarted: 'Commencer', login: 'Se connecter', features: 'Fonctionnalités', featureFlows: 'Processus étape par étape', featureFlowsDesc: 'Suivez des processus guidés pour les demandes de visa, l\'enregistrement et plus.', featureDocs: 'Coffre à documents', featureDocsDesc: 'Stockez et suivez tous vos documents importants avec des alertes d\'expiration.', featureDeadlines: 'Suivi des échéances', featureDeadlinesDesc: 'Ne manquez plus jamais un rendez-vous ou une date de renouvellement.', featureI18n: 'Support multilingue', featureI18nDesc: 'Disponible en 11 langues dont l\'arabe, le turc, l\'ukrainien et plus.', pricing: 'Tarifs', pricingSubtitle: 'Choisissez le plan qui vous convient', free: 'Gratuit', premium: 'Premium', premiumPrice: '€4,99/mois', premiumYearly: '€39,99/an', saveYearly: 'Économisez 33%', currentPlan: 'Plan actuel', upgrade: 'Mettre à niveau', freeTier1: 'Jusqu\'à 3 processus actifs', freeTier2: 'Jusqu\'à 10 documents', freeTier3: 'Suivi basique des échéances', freeTier4: 'Support communautaire', premiumTier1: 'Processus illimités', premiumTier2: 'Documents illimités', premiumTier3: 'Support prioritaire par email', premiumTier4: 'Expérience sans publicité', premiumTier5: 'Export des documents en PDF', premiumTier6: 'Rappels avancés', premiumTier7: 'Liste de vérification personnalisée' },
  auth: { login: 'Se connecter', register: 'Créer un compte', email: 'Email', password: 'Mot de passe', confirmPassword: 'Confirmer le mot de passe', forgotPassword: 'Mot de passe oublié?', noAccount: 'Pas de compte?', hasAccount: 'Déjà un compte?', loginError: 'Email ou mot de passe invalide', registerError: 'Échec de l\'inscription. Veuillez réessayer.', passwordMismatch: 'Les mots de passe ne correspondent pas', checkEmail: 'Vérifiez votre email pour confirmer votre compte', fullName: 'Nom complet', logout: 'Se déconnecter' },
  onboarding: { title: 'Configurons votre profil', subtitle: 'Cela nous aide à personnaliser votre expérience', step1Title: 'Type de visa', step1Desc: 'Quel type de visa avez-vous ou demandez-vous?', step2Title: 'Détails de la demande', step2Desc: 'Dites-nous en plus sur votre situation', step3Title: 'Localisation', step3Desc: 'Où êtes-vous en Allemagne?', visaType: 'Type de visa', applicationType: 'Est-ce votre première demande ou un renouvellement?', firstApplication: 'Première demande', renewal: 'Renouvellement', city: 'Ville', zipCode: 'Code postal', visaExpiry: 'Date d\'expiration du visa', complete: 'Terminer la configuration', step: 'Étape', of: 'sur' },
  dashboard: { title: 'Tableau de bord', welcomeBack: 'Bon retour', yourFlows: 'Vos processus', yourDocuments: 'Vos documents', upcomingDeadlines: 'Échéances à venir', quickActions: 'Actions rapides', startNewFlow: 'Nouveau processus', addDocument: 'Ajouter un document', viewAllFlows: 'Voir tous les processus', viewAllDocs: 'Voir tous les documents', viewAllDeadlines: 'Voir toutes les échéances', noFlows: 'Aucun processus actif', noDocs: 'Aucun document', noDeadlines: 'Aucune échéance à venir', progress: 'Progression', dueIn: 'Dans', days: 'jours', overdue: 'En retard', today: 'Aujourd\'hui', premiumBanner: 'Passer à Premium', premiumBannerDesc: 'Processus illimités, sans publicité et plus.', premiumBannerCta: 'En savoir plus' },
  flows: { title: 'Processus', subtitle: 'Guides étape par étape adaptés à votre type de visa', startFlow: 'Démarrer', continueFlow: 'Continuer', completed: 'Terminé', inProgress: 'En cours', notStarted: 'Non commencé', steps: 'Étapes', step: 'Étape', markDone: 'Marquer comme terminé', markUndone: 'Marquer comme non terminé', notes: 'Notes', addNote: 'Ajouter une note...', saveNote: 'Enregistrer la note', requiredDocs: 'Documents requis', usefulLinks: 'Liens utiles', tips: 'Conseils', optional: 'Étape optionnelle', flowProgress: 'Progression du processus', noFlows: 'Aucun processus disponible pour votre type de visa', backToFlows: 'Retour aux processus', limitReached: 'Limite du plan gratuit atteinte', limitReachedDesc: 'Passez à Premium pour des processus illimités.' },
  docs: { title: 'Documents', subtitle: 'Suivez tous vos documents importants', addDocument: 'Ajouter un document', editDocument: 'Modifier le document', docType: 'Type de document', docName: 'Nom du document', issueDate: 'Date d\'émission', expiryDate: 'Date d\'expiration', status: 'Statut', notes: 'Notes', linkedFlow: 'Processus lié', noDocuments: 'Aucun document ajouté', valid: 'Valide', pending: 'En attente', expired: 'Expiré', notUploaded: 'Non téléchargé', deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ce document?', limitReached: 'Limite du plan gratuit atteinte', limitReachedDesc: 'Passez à Premium pour des documents illimités.' },
  deadlines: { title: 'Échéances', subtitle: 'Ne manquez jamais une date importante', addDeadline: 'Ajouter une échéance', editDeadline: 'Modifier l\'échéance', deadlineTitle: 'Titre', description: 'Description', dueDate: 'Date d\'échéance', remindAt: 'Rappel', markDone: 'Marquer comme terminé', markUndone: 'Marquer comme non terminé', done: 'Terminé', upcoming: 'À venir', overdue: 'En retard', noDeadlines: 'Aucune échéance définie', deleteConfirm: 'Êtes-vous sûr de vouloir supprimer cette échéance?' },
  nav: { dashboard: 'Tableau de bord', flows: 'Processus', documents: 'Documents', deadlines: 'Échéances', settings: 'Paramètres', logout: 'Se déconnecter', language: 'Langue', premium: 'Premium', upgrade: 'Mettre à niveau' },
  visa: { student_visa: 'Visa étudiant', job_seeker_visa: 'Visa recherche d\'emploi', blue_card: 'Carte bleue', work_permit: 'Permis de travail', family_reunion: 'Regroupement familial', freelance_visa: 'Visa freelance', permanent_residence: 'Résidence permanente', other: 'Autre' },
  premium: { title: 'Passer à Premium', subtitle: 'Débloquez toute la puissance du Guide Allemagne', monthly: 'Mensuel', yearly: 'Annuel', monthlyPrice: '€4,99/mois', yearlyPrice: '€39,99/an', savePercent: 'Économisez 33%', subscribe: 'S\'abonner', manage: 'Gérer l\'abonnement', cancel: 'Annuler l\'abonnement', cancelConfirm: 'Êtes-vous sûr de vouloir annuler votre abonnement?', active: 'Actif', cancelled: 'Annulé', expired: 'Expiré', renewsOn: 'Se renouvelle le', expiresOn: 'Expire le', feature1: 'Processus et documents illimités', feature2: 'Sans publicité', feature3: 'Support prioritaire', feature4: 'Export PDF', feature5: 'Rappels avancés (SMS et Email)', feature6: 'Listes personnalisées', thankYou: 'Merci pour votre abonnement!', welcomePremium: 'Bienvenue dans Premium.', paymentSuccess: 'Paiement réussi', paymentCancelled: 'Paiement annulé', returnToDashboard: 'Retour au tableau de bord', processing: 'Traitement du paiement...', error: 'Une erreur est survenue. Veuillez réessayer.' },
  affiliates: { recommended: 'Services recommandés', subtitle: 'Partenaires de confiance pour vous installer en Allemagne', banking: 'Banque', insurance: 'Assurance maladie', mobile: 'Forfaits mobiles', housing: 'Logement', learn: 'En savoir plus', disclaimer: 'Nous pouvons recevoir une commission lorsque vous vous inscrivez via nos liens. Cela n\'affecte pas le prix.', openAccount: 'Ouvrir un compte', getQuote: 'Obtenir un devis', viewPlans: 'Voir les forfaits', findHousing: 'Trouver un logement' },
  support: { tipTitle: 'Soutenir ce projet', tipSubtitle: 'Aidez-nous à garder ce guide gratuit et à jour', tipAmount: 'Choisir un montant', tipCustom: 'Montant personnalisé', tipSend: 'Envoyer un pourboire', tipThankYou: 'Merci pour votre soutien!', tipOneTime: 'Pourboire unique' },
  ads: { sponsored: 'Sponsorisé', advertisement: 'Publicité' },
};

export default fr as unknown as Dictionary;