/* eslint-disable */
import type { Dictionary } from './en';

const hi = {
  common: { appName: 'जर्मनी गाइड', loading: 'लोड हो रहा है...', save: 'सहेजें', cancel: 'रद्द करें', delete: 'हटाएं', edit: 'संपादित करें', back: 'वापस', next: 'अगला', submit: 'जमा करें', yes: 'हाँ', no: 'नहीं', or: 'या', error: 'त्रुटि', success: 'सफलता', close: 'बंद करें', optional: 'वैकल्पिक', required: 'आवश्यक', search: 'खोजें', noResults: 'कोई परिणाम नहीं मिला', confirm: 'पुष्टि करें', welcome: 'स्वागत है' },
  landing: { hero: 'जर्मनी में रहने के लिए आपका पूर्ण मार्गदर्शक', subtitle: 'नौकरशाही को समझें, दस्तावेज़ प्रबंधित करें और समय सीमा ट्रैक करें — सब एक जगह।', getStarted: 'शुरू करें', login: 'लॉग इन', features: 'सुविधाएँ', featureFlows: 'चरण-दर-चरण प्रक्रियाएँ', featureFlowsDesc: 'वीजा आवेदन, शहर पंजीकरण और अधिक के लिए निर्देशित प्रक्रियाओं का पालन करें।', featureDocs: 'दस्तावेज़ तिजोरी', featureDocsDesc: 'समाप्ति अलर्ट के साथ सभी महत्वपूर्ण दस्तावेज़ स्टोर और ट्रैक करें।', featureDeadlines: 'समय सीमा ट्रैकर', featureDeadlinesDesc: 'फिर कभी कोई अपॉइंटमेंट या नवीनीकरण तिथि न चूकें।', featureI18n: 'बहुभाषी समर्थन', featureI18nDesc: 'अरबी, तुर्की, यूक्रेनी और अधिक सहित 11 भाषाओं में उपलब्ध।', pricing: 'मूल्य निर्धारण', pricingSubtitle: 'अपने लिए सही योजना चुनें', free: 'मुफ्त', premium: 'प्रीमियम', premiumPrice: '€4.99/माह', premiumYearly: '€39.99/वर्ष', saveYearly: '33% बचाएं', currentPlan: 'वर्तमान योजना', upgrade: 'अभी अपग्रेड करें', freeTier1: '3 सक्रिय प्रक्रियाएँ तक', freeTier2: '10 दस्तावेज़ तक', freeTier3: 'बुनियादी समय सीमा ट्रैकिंग', freeTier4: 'सामुदायिक सहायता', premiumTier1: 'असीमित प्रक्रियाएँ', premiumTier2: 'असीमित दस्तावेज़', premiumTier3: 'प्राथमिकता ईमेल सहायता', premiumTier4: 'विज्ञापन-मुक्त अनुभव', premiumTier5: 'दस्तावेज़ PDF में निर्यात करें', premiumTier6: 'उन्नत समय सीमा रिमाइंडर', premiumTier7: 'व्यक्तिगत चेकलिस्ट' },
  auth: { login: 'लॉग इन', register: 'खाता बनाएं', email: 'ईमेल', password: 'पासवर्ड', confirmPassword: 'पासवर्ड पुष्टि करें', forgotPassword: 'पासवर्ड भूल गए?', noAccount: 'खाता नहीं है?', hasAccount: 'पहले से खाता है?', loginError: 'अमान्य ईमेल या पासवर्ड', registerError: 'पंजीकरण विफल। कृपया पुनः प्रयास करें।', passwordMismatch: 'पासवर्ड मेल नहीं खाते', checkEmail: 'अपना खाता सत्यापित करने के लिए ईमेल जांचें', fullName: 'पूरा नाम', logout: 'लॉग आउट' },
  onboarding: { title: 'अपनी प्रोफ़ाइल सेट करें', subtitle: 'इससे हमें आपके अनुभव को निजीकृत करने में मदद मिलती है', step1Title: 'वीजा प्रकार', step1Desc: 'आपके पास किस प्रकार का वीजा है या आप आवेदन कर रहे हैं?', step2Title: 'आवेदन विवरण', step2Desc: 'अपनी स्थिति के बारे में और बताएं', step3Title: 'स्थान', step3Desc: 'जर्मनी में आप कहाँ हैं?', visaType: 'वीजा प्रकार', applicationType: 'यह पहला आवेदन है या नवीनीकरण?', firstApplication: 'पहला आवेदन', renewal: 'नवीनीकरण', city: 'शहर', zipCode: 'पिन कोड', visaExpiry: 'वीजा समाप्ति तिथि', complete: 'सेटअप पूरा करें', step: 'चरण', of: 'का' },
  dashboard: { title: 'डैशबोर्ड', welcomeBack: 'वापसी पर स्वागत', yourFlows: 'आपकी प्रक्रियाएँ', yourDocuments: 'आपके दस्तावेज़', upcomingDeadlines: 'आगामी समय सीमाएं', quickActions: 'त्वरित कार्रवाई', startNewFlow: 'नई प्रक्रिया शुरू करें', addDocument: 'दस्तावेज़ जोड़ें', viewAllFlows: 'सभी प्रक्रियाएँ देखें', viewAllDocs: 'सभी दस्तावेज़ देखें', viewAllDeadlines: 'सभी समय सीमाएं देखें', noFlows: 'कोई सक्रिय प्रक्रिया नहीं', noDocs: 'कोई दस्तावेज़ नहीं', noDeadlines: 'कोई आगामी समय सीमा नहीं', progress: 'प्रगति', dueIn: 'शेष', days: 'दिन', overdue: 'अतिदेय', today: 'आज', premiumBanner: 'प्रीमियम में अपग्रेड करें', premiumBannerDesc: 'असीमित प्रक्रियाएँ, विज्ञापन-मुक्त अनुभव और अधिक।', premiumBannerCta: 'और जानें' },
  flows: { title: 'प्रक्रियाएँ', subtitle: 'आपके वीजा प्रकार के लिए चरण-दर-चरण मार्गदर्शिकाएं', startFlow: 'शुरू करें', continueFlow: 'जारी रखें', completed: 'पूर्ण', inProgress: 'प्रगति में', notStarted: 'शुरू नहीं हुआ', steps: 'चरण', step: 'चरण', markDone: 'पूर्ण चिह्नित करें', markUndone: 'अपूर्ण चिह्नित करें', notes: 'नोट्स', addNote: 'नोट जोड़ें...', saveNote: 'नोट सहेजें', requiredDocs: 'आवश्यक दस्तावेज़', usefulLinks: 'उपयोगी लिंक', tips: 'सुझाव', optional: 'वैकल्पिक चरण', flowProgress: 'प्रक्रिया प्रगति', noFlows: 'आपके वीजा प्रकार के लिए कोई प्रक्रिया उपलब्ध नहीं', backToFlows: 'प्रक्रियाओं पर वापस', limitReached: 'मुफ्त योजना सीमा पहुंची', limitReachedDesc: 'असीमित प्रक्रियाओं के लिए प्रीमियम में अपग्रेड करें।' },
  docs: { title: 'दस्तावेज़', subtitle: 'सभी महत्वपूर्ण दस्तावेज़ ट्रैक करें', addDocument: 'दस्तावेज़ जोड़ें', editDocument: 'दस्तावेज़ संपादित करें', docType: 'दस्तावेज़ प्रकार', docName: 'दस्तावेज़ नाम', issueDate: 'जारी तिथि', expiryDate: 'समाप्ति तिथि', status: 'स्थिति', notes: 'नोट्स', linkedFlow: 'लिंक्ड प्रक्रिया', noDocuments: 'कोई दस्तावेज़ नहीं जोड़ा गया', valid: 'वैध', pending: 'लंबित', expired: 'समाप्त', notUploaded: 'अपलोड नहीं किया गया', deleteConfirm: 'क्या आप वाकई इस दस्तावेज़ को हटाना चाहते हैं?', limitReached: 'मुफ्त योजना सीमा पहुंची', limitReachedDesc: 'असीमित दस्तावेज़ों के लिए प्रीमियम में अपग्रेड करें।' },
  deadlines: { title: 'समय सीमाएं', subtitle: 'कोई महत्वपूर्ण तिथि न चूकें', addDeadline: 'समय सीमा जोड़ें', editDeadline: 'समय सीमा संपादित करें', deadlineTitle: 'शीर्षक', description: 'विवरण', dueDate: 'नियत तिथि', remindAt: 'रिमाइंडर', markDone: 'पूर्ण चिह्नित करें', markUndone: 'अपूर्ण चिह्नित करें', done: 'पूर्ण', upcoming: 'आगामी', overdue: 'अतिदेय', noDeadlines: 'कोई समय सीमा नहीं', deleteConfirm: 'क्या आप वाकई इस समय सीमा को हटाना चाहते हैं?' },
  nav: { dashboard: 'डैशबोर्ड', flows: 'प्रक्रियाएँ', documents: 'दस्तावेज़', deadlines: 'समय सीमाएं', settings: 'सेटिंग्स', logout: 'लॉग आउट', language: 'भाषा', premium: 'प्रीमियम', upgrade: 'अपग्रेड' },
  visa: { student_visa: 'छात्र वीजा', job_seeker_visa: 'नौकरी खोज वीजा', blue_card: 'ब्लू कार्ड', work_permit: 'कार्य परमिट', family_reunion: 'परिवार पुनर्मिलन', freelance_visa: 'फ्रीलांस वीजा', permanent_residence: 'स्थायी निवास', other: 'अन्य' },
  premium: { title: 'प्रीमियम में अपग्रेड करें', subtitle: 'जर्मनी गाइड की पूरी शक्ति अनलॉक करें', monthly: 'मासिक', yearly: 'वार्षिक', monthlyPrice: '€4.99/माह', yearlyPrice: '€39.99/वर्ष', savePercent: '33% बचाएं', subscribe: 'अभी सब्सक्राइब करें', manage: 'सब्सक्रिप्शन प्रबंधित करें', cancel: 'सब्सक्रिप्शन रद्द करें', cancelConfirm: 'क्या आप वाकई सब्सक्रिप्शन रद्द करना चाहते हैं?', active: 'सक्रिय', cancelled: 'रद्द', expired: 'समाप्त', renewsOn: 'नवीनीकरण तिथि', expiresOn: 'समाप्ति तिथि', feature1: 'असीमित प्रक्रियाएँ और दस्तावेज़', feature2: 'विज्ञापन-मुक्त अनुभव', feature3: 'प्राथमिकता सहायता', feature4: 'PDF निर्यात', feature5: 'उन्नत रिमाइंडर (SMS और ईमेल)', feature6: 'व्यक्तिगत चेकलिस्ट', thankYou: 'सब्सक्राइब करने के लिए धन्यवाद!', welcomePremium: 'प्रीमियम में स्वागत है।', paymentSuccess: 'भुगतान सफल', paymentCancelled: 'भुगतान रद्द', returnToDashboard: 'डैशबोर्ड पर वापस', processing: 'भुगतान प्रोसेस हो रहा है...', error: 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।' },
  affiliates: { recommended: 'अनुशंसित सेवाएं', subtitle: 'जर्मनी में बसने में मदद के लिए विश्वसनीय साझेदार', banking: 'बैंकिंग', insurance: 'स्वास्थ्य बीमा', mobile: 'मोबाइल प्लान', housing: 'आवास', learn: 'और जानें', disclaimer: 'हमारे लिंक से साइन अप करने पर हमें कमीशन मिल सकता है। इससे आपकी कीमत प्रभावित नहीं होती।', openAccount: 'खाता खोलें', getQuote: 'कोटेशन लें', viewPlans: 'प्लान देखें', findHousing: 'आवास खोजें', bankingDesc: '\u092E\u0941\u092B\u094D\u0924 \u091C\u0930\u094D\u092E\u0928 \u092C\u0948\u0902\u0915 \u0916\u093E\u0924\u093E, \u0915\u093E\u0917\u091C\u093E\u0924 \u0928\u0939\u0940\u0902\u0964 8 \u092E\u093F\u0928\u091F \u092E\u0947\u0902 \u0916\u094B\u0932\u0947\u0902\u0964', insuranceDesc: '\u091C\u0930\u094D\u092E\u0928\u0940 \u0915\u093E \u0938\u092C\u0938\u0947 \u092C\u0921\u093C\u093E \u0938\u093E\u0930\u094D\u0935\u091C\u0928\u093F\u0915 \u0938\u094D\u0935\u093E\u0938\u094D\u0925\u094D\u092F \u092C\u0940\u092E\u093E\u0964 \u0905\u0902\u0917\u094D\u0930\u0947\u091C\u0940 \u0938\u0939\u093E\u092F\u0924\u093E \u0909\u092A\u0932\u092C\u094D\u0927\u0964', mobileDesc: '10 \u092F\u0942\u0930\u094B/\u092E\u093E\u0939 \u0938\u0947 \u0936\u0941\u0930\u0942 \u0938\u0930\u0932 \u092E\u094B\u092C\u093E\u0907\u0932 \u092A\u094D\u0932\u093E\u0928\u0964 \u0915\u094B\u0908 \u0905\u0928\u0941\u092C\u0902\u0927 \u0928\u0939\u0940\u0902\u0964', housingDesc: '\u0938\u093E\u091D\u093E \u0905\u092A\u093E\u0930\u094D\u091F\u092E\u0947\u0902\u091F \u0914\u0930 \u0906\u0935\u093E\u0938 \u0915\u0947 \u0932\u093F\u090F \u091C\u0930\u094D\u092E\u0928\u0940 \u0915\u093E \u0928\u0902\u092C\u0930 1 \u092A\u094D\u0932\u0947\u091F\u0911\u0930\u094D\u092E\u0964' },
  support: { tipTitle: 'इस प्रोजेक्ट का समर्थन करें', tipSubtitle: 'इस गाइड को मुफ्त और अपडेट रखने में मदद करें', tipAmount: 'राशि चुनें', tipCustom: 'कस्टम राशि', tipSend: 'टिप भेजें', tipThankYou: 'आपके समर्थन के लिए धन्यवाद!', tipOneTime: 'एकबारगी टिप' },
  ads: { sponsored: 'प्रायोजित', advertisement: 'विज्ञापन' },
};

export default hi as unknown as Dictionary;