import type { Dictionary } from "./en";
const hu = {
  common: { appName: "Germany Guide", loading: "Betoltes...", save: "Mentes", cancel: "Megse", delete: "Torles", edit: "Szerkesztes", back: "Vissza", next: "Kovetkezo", submit: "Kuldes", search: "Kereses", filter: "Szures", sortBy: "Rendezes", noResults: "Nincs talalat", error: "Hiba tortent", success: "Sikeres", confirm: "Megerosites", yes: "Igen", no: "Nem", close: "Bezaras", language: "Nyelv", logout: "Kijelentkezes" },
  landing: { heroTitle: "Navigaljon a nemet burokraciaaban magabiztosan", heroSubtitle: "Lepesrol lepesre utmutatok vizumokhoz, regisztraciohoz es nemetorszagi letelepuleshez. 11 nyelven elerheto.", getStarted: "Ingyenes kezdes", learnMore: "Tovabbi informaciok", featuresTitle: "Minden ami szukseges a nemetorszagi letelepuleshez", feature1Title: "Vizum folyamat motor", feature1Desc: "Szemelyre szabott lepesrol lepesre utmutatok a vizum tipusa, varos es kerelmi tipus alapjan.", feature2Title: "Dokumentumtar", feature2Desc: "Kovesse nyomon osszes fontos dokumentumat, lejarati datumait es statuszait egy helyen.", feature3Title: "Hatarido emlekeztetok", feature3Desc: "Soha ne mulasszon el vizum megujitast vagy idopontot.", feature4Title: "11 nyelv", feature4Desc: "Elerheto magyarul, nemetul, angolul, arabul, torokul, ukranul es mas nyelveken.", howItWorksTitle: "Hogyan mukodik", step1Title: "Hozzon letre fiokot", step1Desc: "Regisztraljon ingyenesen es mondja el vizum tipusat.", step2Title: "Kovesse a folyamatot", step2Desc: "Kapjon szemelyre szabott ellenorzo listat.", step3Title: "Kovesse nyomon a halaadasat", step3Desc: "Jeloelje meg a lepeseket befejezettnek.", ctaTitle: "Keszen all a nemetorszagi koltozes egyszerusitesere?", ctaSubtitle: "Csatlakozzon ezrekhez.", ctaButton: "Ingyenes fiok letrehozasa", pricingTitle: "Egyszeru es atlathhato arazas", pricingSubtitle: "Kezdje ingyenesen. Frissitsen ha szukseges.", freeTier: "Ingyenes", premiumTier: "Premium", freePriceLabel: "Orokre ingyenes", freeFeature1: "Legfeljebb 3 aktiv folyamat", freeFeature2: "Legfeljebb 10 dokumentum", freeFeature3: "Alap hatarido kovetes", freeFeature4: "Mind a 11 nyelv", premiumFeature1: "Korlatlan folyamatok", premiumFeature2: "Korlatlan dokumentumok", premiumFeature3: "Elsobbsegi emlekeztetok", premiumFeature4: "Reklammenetes elmeny", premiumFeature5: "PDF exportalas", premiumMonthly: "Havi", premiumYearly: "Eves" },
  auth: { loginTitle: "Udvoezoljuk ujra", loginSubtitle: "Jelentkezzen be Germany Guide fiokjaba", registerTitle: "Fiok letrehozasa", registerSubtitle: "Kezdje meg nemetorszagi utjat", email: "Email", password: "Jelszo", confirmPassword: "Jelszo megerositese", fullName: "Teljes nev", signIn: "Bejelentkezes", signUp: "Regisztracio", forgotPassword: "Elfelejtett jelszo?", noAccount: "Nincs fiokja?", hasAccount: "Mar van fiokja?", signUpLink: "Regisztracio", signInLink: "Bejelentkezes", orContinueWith: "Vagy folytassa ezzel", google: "Google", passwordMismatch: "A jelszavak nem egyeznek", createOne: "Hozzon letre egyet", registerDesc: "Adja meg adatait az ingyenes fiok letrehozasahoz", passwordHint: "Legalabb 6 karakter", passwordTooShort: "A jelozonak legalabb 6 karakternek kell lennie" },
  onboarding: { title: "Profil beallitasa", subtitle: "Meseljen magarol hogy szemelyre szabhassuk az elmenyet", visaType: "Vizum tipusa", selectVisaType: "Valassza ki vizum tipusat", applicationType: "Kerelmi tipus", firstApplication: "Elso kerelem", renewal: "Megujitas", city: "Varos", selectCity: "Valassza ki varosat", zipCode: "Iranyitoszam", enterZipCode: "Adja meg iranyitoszamat", visaExpiry: "Vizum lejarati datuma", step1Title: "Vizum informaciok", step1Desc: "Milyen tipusu vizummal rendelkezik?", step2Title: "Helyszin", step2Desc: "Hol el Nemetorszagban?", step3Title: "Fontos datumok", step3Desc: "Mikor jar le a vizuma?", complete: "Beallitas befejezese", skipForNow: "Kihagyas", progress: "{current}. lepes a {total}-bol", visaPlaceholder: "Valasszon vizum tipust", cityPlaceholder: "Valasszon varost", zipPlaceholder: "pl. 10115", expiryHint: "Ez segit megujitasi emlekeztetok kuldeseben", aboutYou: "Onrol", location: "Helyszin", completeSetup: "Beallitas befejezese", saveChanges: "Valtozasok mentese", welcome: "Udvoezoljuk a Germany Guide-ban" },
  dashboard: { title: "Iranyitopult", welcome: "Udvoezoljuk ujra", quickActions: "Gyors muveletek", recentFlows: "Legutobbi folyamatok", upcomingDeadlines: "Kozeli hataridok", documentStatus: "Dokumentum statusz", noFlows: "Meg nincs aktiv folyamat", noDeadlines: "Nincs kozeli hatarido", startFlow: "Uj folyamat inditasa", viewAll: "Osszes megtekintese", yourProgress: "Az On haladasa", completedSteps: "Befejezett lepesek", activeFlows: "Aktiv folyamatok", totalDocuments: "Osszes dokumentum", overview: "Attekintes", premiumBanner: "Frissites Premiumra", premiumBannerDesc: "Korlatlan folyamatok, dokumentumok, reklammenetes elmeny.", premiumBannerCta: "Frissites most", tipCard: "Tamogassa a Germany Guide-ot", tipCardDesc: "Segitsen a szolgaltatas fenntartasaban.", tipCardCta: "Borravalo adasaa" },
  flows: { title: "Folyamatai", startNew: "Uj folyamat", progress: "{percent}% kesz", steps: "{count} lepes", completed: "Befejezve", inProgress: "Folyamatban", notStarted: "Nem kezdett", continueFlow: "Folytatas", viewDetails: "Reszletek", stepOf: "{current}. lepes a {total}-bol", markDone: "Befejezettnek jeloeloese", markUndone: "Befejezetlennek jeloelese", notes: "Jegyzetek", addNote: "Jegyzet hozzaadasa...", requiredDocs: "Szukseges dokumentumok", usefulLinks: "Hasznos linkek", tips: "Tippek", optional: "Opcionalis", flowCompleted: "Folyamat befejezve!", allStepsDone: "Az osszes lepest elveegezte.", backToFlows: "Vissza a folyamatokhoz", previousStep: "Elozo", nextStep: "Kovetkezo", recommended: "Ajanlott Onnek", myFlows: "Folyamataim", recommendedForYou: "Ajanlott Onnek", basedOnVisa: "Vizum tipusa alapjan", otherFlows: "Egyeb folyamatok", yourNotes: "Az On jegyzetei", undo: "Visszavonas", markAsDone: "Befejezettnek jeloeloese", completedSection: "Befejezve" },
  docs: { title: "Dokumentumok", addNew: "Dokumentum hozzaadasa", docType: "Dokumentum tipusa", docName: "Dokumentum neve", issueDate: "Kiallitas datuma", expiryDate: "Lejarati datum", status: "Statusz", valid: "Ervenyes", pending: "Fueggoben", expired: "Lejart", notUploaded: "Nem feltoltott", linkedFlow: "Kapcsolt folyamat", noDocuments: "Meg nincs dokumentum", addFirst: "Adja hozza elso dokumentumat", selectDocType: "Valasszon tipust", enterDocName: "Adja meg a nevet", saveDocument: "Dokumentum mentese", deleteConfirm: "Biztosan torolni szeretne?", notesPlaceholder: "Jegyzet hozzaadasa...", documentVault: "Dokumentumtar", addNewDocument: "Uj dokumentum hozzaadasa", backToDocuments: "Vissza a dokumentumokhoz", selectTypeAndName: "Valasszon tipust es nevet", linkToFlow: "Kapcsolas folyamathoz", none: "Nincs", issued: "Kiallitva", expires: "Lejar", expiringSoon: "Hamarosan lejar" },
  deadlines: { title: "Hataridok", addNew: "Hatarido hozzaadasa", dueDate: "Hatarido", reminder: "Emlekeztetoe", done: "Kesz", pending: "Fueggoben", overdue: "Lejart", noDeadlines: "Nincs hatarido", addFirst: "Adjon hozza egy hataridot", deadlineTitle: "Cim", description: "Leiras", setReminder: "Emlekeztetoe beallitasa", reminderDate: "Emlekeztetoe datuma", saveDeadline: "Mentes", markComplete: "Befejezettnek jeloeloese", deleteConfirm: "Biztosan torolni szeretne?", titlePlaceholder: "pl. Vizum megujitas", descPlaceholder: "Reszletek hozzaadasa...", titleDesc: "Cim es leiras", addNewDeadline: "Uj hatarido hozzaadasa", due: "Hatarido", daysLeft: "nap van hatra", startReminding: "Emlekeztetoes inditasa", noPending: "Nincs fuggo hatarido", completedSection: "Befejezett hataridok", titleAndDateRequired: "A cim es a datum kotelezo" },
  nav: { dashboard: "Iranyitopult", flows: "Folyamatok", documents: "Dokumentumok", deadlines: "Hataridok", settings: "Beallitasok", help: "Segitseg", profile: "Profil", premium: "Premium", upgrade: "Frissites" },
  visa: { student_visa: "Diakvizum", job_seeker_visa: "Allaskereso vizum", blue_card: "EU Kek Kartya", work_permit: "Munkavallalasi engedely", family_reunion: "Csaladegyesites", freelance_visa: "Szabaduszo vizum", permanent_residence: "Allandeo tartozkodasi engedely", other: "Egyeb" },
  premium: { title: "Frissites Premiumra", subtitle: "Minden funkcio feloldasa es a hirdetesek eltavolitasa", monthly: "Havi", yearly: "Eves", monthlyPrice: "4,99", yearlyPrice: "39,99", perMonth: "/ho", perYear: "/ev", savePercent: "33% megtakaritas", subscribe: "Feliratkozas most", currentPlan: "Jelenlegi terv", managePlan: "Elofizetes kezelese", cancelAnytime: "Barmikor lemondhhato", feature1: "Korlatlan folyamatok", feature2: "Korlatlan dokumentumok", feature3: "Elsoebbsegi emlekeztetok", feature4: "Reklammenetes elmeny", feature5: "PDF exportalas", feature6: "Elsoebbsegi tamogatas", free: "Ingyenes", premiumBadge: "Premium", upgradeNow: "Frissites most", included: "Tartalmazva", notIncluded: "Nem tartalmazva", mostPopular: "Legnepszeruebb", bestValue: "Legjobb ertek", successTitle: "Udvoezoljuk a Premiumban!", successDesc: "Elofizetese most aktiv.", goToDashboard: "Iranyitopultra", billedMonthly: "Havi szamlazas", billedYearly: "Eves szamlazas" },
  affiliates: { title: "Ajanlott szolgaltatasok", subtitle: "Megbizhato szolgaltatasok a nemetorszagi letelepuleshez", banking: "N26", insurance: "TK", mobile: "Fraenk", housing: "WG-Gesucht", visitSite: "Weboldal latogatasa", sponsored: "Partner", bankingDesc: "Ingyenes digitalis bankszamla. Percek alatt nyithato.", insuranceDesc: "Nemetorszag legjobb allami egeszsegbiztositasa.", mobileDesc: "Egyszeru mobil csomagok havi 5 eurotol.", housingDesc: "Talaljon kozos lakasokat egesz Nemetorszagban.", bankingTag: "Bankolas", insuranceTag: "Biztositas", mobileTag: "Mobil", housingTag: "Lakas" },
  support: { title: "Tamogassa a Germany Guide-ot", subtitle: "Segitsen fenntartani ezt az ingyenes szolgaltatast", tipAmount: "Borravalo osszege", customAmount: "Egyedi osszeg", sendTip: "Borravalo kuldese", thankYouTitle: "Koszonjoek a tamogatasat!", thankYouDesc: "Borravaloja segit a Germany Guide fejleszteseben." },
  ads: { placeholder: "Hirdetes", hiddenForPremium: "A hirdetesek rejtve vannak a premium felhasznalok szamara" },
  privacy: { title: "Adatvedelmi iranyelevek" },
  terms: { title: "Szolgaltatasi feltetelek" },
  about: { title: "A Germany Guide-rol" },
} as unknown as Dictionary;
export default hu;