/* eslint-disable */
import type { Dictionary } from './en';

const ru = {
  common: { appName: 'Гид по Германии', loading: 'Загрузка...', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Редактировать', back: 'Назад', next: 'Далее', submit: 'Отправить', yes: 'Да', no: 'Нет', or: 'или', error: 'Ошибка', success: 'Успех', close: 'Закрыть', optional: 'Необязательно', required: 'Обязательно', search: 'Поиск', noResults: 'Ничего не найдено', confirm: 'Подтвердить', welcome: 'Добро пожаловать' },
  landing: { hero: 'Ваш полный гид по жизни в Германии', subtitle: 'Ориентируйтесь в бюрократии, управляйте документами и отслеживайте сроки — всё в одном месте.', getStarted: 'Начать', login: 'Войти', features: 'Возможности', featureFlows: 'Пошаговые процессы', featureFlowsDesc: 'Следуйте руководствам для визовых заявок, регистрации и многого другого.', featureDocs: 'Хранилище документов', featureDocsDesc: 'Храните и отслеживайте все важные документы с уведомлениями об истечении срока.', featureDeadlines: 'Отслеживание сроков', featureDeadlinesDesc: 'Больше никогда не пропустите встречу или дату продления.', featureI18n: 'Многоязычная поддержка', featureI18nDesc: 'Доступно на 11 языках, включая арабский, турецкий, украинский и другие.', pricing: 'Цены', pricingSubtitle: 'Выберите подходящий план', free: 'Бесплатно', premium: 'Премиум', premiumPrice: '€4.99/месяц', premiumYearly: '€39.99/год', saveYearly: 'Экономия 33%', currentPlan: 'Текущий план', upgrade: 'Обновить сейчас', freeTier1: 'До 3 активных процессов', freeTier2: 'До 10 документов', freeTier3: 'Базовое отслеживание сроков', freeTier4: 'Поддержка сообщества', premiumTier1: 'Безлимитные процессы', premiumTier2: 'Безлимитные документы', premiumTier3: 'Приоритетная поддержка по email', premiumTier4: 'Без рекламы', premiumTier5: 'Экспорт документов в PDF', premiumTier6: 'Расширенные напоминания', premiumTier7: 'Персонализированный чек-лист' },
  auth: { login: 'Войти', register: 'Создать аккаунт', email: 'Электронная почта', password: 'Пароль', confirmPassword: 'Подтвердить пароль', forgotPassword: 'Забыли пароль?', noAccount: 'Нет аккаунта?', hasAccount: 'Уже есть аккаунт?', loginError: 'Неверная почта или пароль', registerError: 'Ошибка регистрации. Попробуйте снова.', passwordMismatch: 'Пароли не совпадают', checkEmail: 'Проверьте почту для подтверждения', fullName: 'Полное имя', logout: 'Выйти' },
  onboarding: { title: 'Настройте свой профиль', subtitle: 'Это поможет нам персонализировать ваш опыт', step1Title: 'Тип визы', step1Desc: 'Какой тип визы у вас есть или вы подаёте заявку?', step2Title: 'Детали заявки', step2Desc: 'Расскажите подробнее о вашей ситуации', step3Title: 'Местоположение', step3Desc: 'Где вы находитесь в Германии?', visaType: 'Тип визы', applicationType: 'Это ваша первая заявка или продление?', firstApplication: 'Первая заявка', renewal: 'Продление', city: 'Город', zipCode: 'Почтовый индекс', visaExpiry: 'Дата истечения визы', complete: 'Завершить настройку', step: 'Шаг', of: 'из' },
  dashboard: { title: 'Панель управления', welcomeBack: 'С возвращением', yourFlows: 'Ваши процессы', yourDocuments: 'Ваши документы', upcomingDeadlines: 'Ближайшие сроки', quickActions: 'Быстрые действия', startNewFlow: 'Новый процесс', addDocument: 'Добавить документ', viewAllFlows: 'Все процессы', viewAllDocs: 'Все документы', viewAllDeadlines: 'Все сроки', noFlows: 'Нет активных процессов', noDocs: 'Нет документов', noDeadlines: 'Нет ближайших сроков', progress: 'Прогресс', dueIn: 'Через', days: 'дней', overdue: 'Просрочено', today: 'Сегодня', premiumBanner: 'Обновить до Премиум', premiumBannerDesc: 'Безлимитные процессы, без рекламы и многое другое.', premiumBannerCta: 'Узнать больше' },
  flows: { title: 'Процессы', subtitle: 'Пошаговые руководства для вашего типа визы', startFlow: 'Начать', continueFlow: 'Продолжить', completed: 'Завершено', inProgress: 'В процессе', notStarted: 'Не начато', steps: 'Шаги', step: 'Шаг', markDone: 'Отметить выполненным', markUndone: 'Отметить невыполненным', notes: 'Заметки', addNote: 'Добавить заметку...', saveNote: 'Сохранить заметку', requiredDocs: 'Необходимые документы', usefulLinks: 'Полезные ссылки', tips: 'Советы', optional: 'Необязательный шаг', flowProgress: 'Прогресс процесса', noFlows: 'Нет процессов для вашего типа визы', backToFlows: 'К процессам', limitReached: 'Достигнут лимит бесплатного плана', limitReachedDesc: 'Обновите до Премиум для безлимитных процессов.' },
  docs: { title: 'Документы', subtitle: 'Отслеживайте все важные документы', addDocument: 'Добавить документ', editDocument: 'Редактировать документ', docType: 'Тип документа', docName: 'Название документа', issueDate: 'Дата выдачи', expiryDate: 'Дата истечения', status: 'Статус', notes: 'Заметки', linkedFlow: 'Связанный процесс', noDocuments: 'Документов пока нет', valid: 'Действителен', pending: 'Ожидает', expired: 'Истёк', notUploaded: 'Не загружен', deleteConfirm: 'Вы уверены, что хотите удалить этот документ?', limitReached: 'Достигнут лимит бесплатного плана', limitReachedDesc: 'Обновите до Премиум для безлимитных документов.' },
  deadlines: { title: 'Сроки', subtitle: 'Никогда не пропустите важную дату', addDeadline: 'Добавить срок', editDeadline: 'Редактировать срок', deadlineTitle: 'Заголовок', description: 'Описание', dueDate: 'Дата', remindAt: 'Напомнить', markDone: 'Выполнено', markUndone: 'Не выполнено', done: 'Выполнено', upcoming: 'Ближайшие', overdue: 'Просроченные', noDeadlines: 'Сроков нет', deleteConfirm: 'Вы уверены, что хотите удалить этот срок?' },
  nav: { dashboard: 'Панель', flows: 'Процессы', documents: 'Документы', deadlines: 'Сроки', settings: 'Настройки', logout: 'Выйти', language: 'Язык', premium: 'Премиум', upgrade: 'Обновить' },
  visa: { student_visa: 'Студенческая виза', job_seeker_visa: 'Виза для поиска работы', blue_card: 'Голубая карта', work_permit: 'Разрешение на работу', family_reunion: 'Воссоединение семьи', freelance_visa: 'Фриланс виза', permanent_residence: 'Постоянное проживание', other: 'Другое' },
  premium: { title: 'Обновить до Премиум', subtitle: 'Разблокируйте все возможности Гида по Германии', monthly: 'Ежемесячно', yearly: 'Ежегодно', monthlyPrice: '€4.99/мес', yearlyPrice: '€39.99/год', savePercent: 'Экономия 33%', subscribe: 'Подписаться', manage: 'Управление подпиской', cancel: 'Отменить подписку', cancelConfirm: 'Вы уверены, что хотите отменить подписку?', active: 'Активна', cancelled: 'Отменена', expired: 'Истекла', renewsOn: 'Продлевается', expiresOn: 'Истекает', feature1: 'Безлимитные процессы и документы', feature2: 'Без рекламы', feature3: 'Приоритетная поддержка', feature4: 'Экспорт PDF', feature5: 'Расширенные напоминания (SMS и Email)', feature6: 'Персонализированные чек-листы', thankYou: 'Спасибо за подписку!', welcomePremium: 'Добро пожаловать в Премиум.', paymentSuccess: 'Оплата прошла успешно', paymentCancelled: 'Оплата отменена', returnToDashboard: 'Вернуться на панель', processing: 'Обработка оплаты...', error: 'Что-то пошло не так. Попробуйте снова.' },
  affiliates: { recommended: 'Рекомендуемые услуги', subtitle: 'Надёжные партнёры для обустройства в Германии', banking: 'Банковские услуги', insurance: 'Медицинское страхование', mobile: 'Мобильные тарифы', housing: 'Жильё', learn: 'Подробнее', disclaimer: 'Мы можем получать комиссию при регистрации по нашим ссылкам. Это не влияет на цену.', openAccount: 'Открыть счёт', getQuote: 'Получить предложение', viewPlans: 'Смотреть тарифы', findHousing: 'Найти жильё', bankingDesc: '\u0411\u0435\u0441\u043F\u043B\u0430\u0442\u043D\u044B\u0439 \u043D\u0435\u043C\u0435\u0446\u043A\u0438\u0439 \u0431\u0430\u043D\u043A\u043E\u0432\u0441\u043A\u0438\u0439 \u0441\u0447\u0451\u0442, \u0431\u0435\u0437 \u0431\u0443\u043C\u0430\u0433. \u041E\u0442\u043A\u0440\u043E\u0439\u0442\u0435 \u0437\u0430 8 \u043C\u0438\u043D\u0443\u0442.', insuranceDesc: '\u041A\u0440\u0443\u043F\u043D\u0435\u0439\u0448\u0435\u0435 \u0433\u043E\u0441\u0443\u0434\u0430\u0440\u0441\u0442\u0432\u0435\u043D\u043D\u043E\u0435 \u043C\u0435\u0434\u0441\u0442\u0440\u0430\u0445\u043E\u0432\u0430\u043D\u0438\u0435 \u0413\u0435\u0440\u043C\u0430\u043D\u0438\u0438. \u041F\u043E\u0434\u0434\u0435\u0440\u0436\u043A\u0430 \u043D\u0430 \u0430\u043D\u0433\u043B\u0438\u0439\u0441\u043A\u043E\u043C.', mobileDesc: '\u041F\u0440\u043E\u0441\u0442\u044B\u0435 \u043C\u043E\u0431\u0438\u043B\u044C\u043D\u044B\u0435 \u0442\u0430\u0440\u0438\u0444\u044B \u043E\u0442 10 \u0435\u0432\u0440\u043E/\u043C\u0435\u0441. \u0411\u0435\u0437 \u043A\u043E\u043D\u0442\u0440\u0430\u043A\u0442\u0430.', housingDesc: '\u041F\u043B\u0430\u0442\u0444\u043E\u0440\u043C\u0430 \u21161 \u0432 \u0413\u0435\u0440\u043C\u0430\u043D\u0438\u0438 \u0434\u043B\u044F \u043F\u043E\u0438\u0441\u043A\u0430 \u0436\u0438\u043B\u044C\u044F.' },
  support: { tipTitle: 'Поддержите проект', tipSubtitle: 'Помогите нам сохранить гид бесплатным и актуальным', tipAmount: 'Выберите сумму', tipCustom: 'Произвольная сумма', tipSend: 'Отправить', tipThankYou: 'Спасибо за поддержку!', tipOneTime: 'Разовая поддержка' },
  ads: { sponsored: 'Спонсировано', advertisement: 'Реклама' },
};

export default ru as unknown as Dictionary;