import type { Dictionary } from "./en";
const tr = {
  common: { appName: "Germany Guide", loading: "Yuekleniyor...", save: "Kaydet", cancel: "Iptal", delete: "Sil", edit: "Duezenle", back: "Geri", next: "Ileri", submit: "Goender", search: "Ara", filter: "Filtrele", sortBy: "Sirala", noResults: "Sonuc bulunamadi", error: "Bir hata olustu", success: "Basarili", confirm: "Onayla", yes: "Evet", no: "Hayir", close: "Kapat", language: "Dil", logout: "Cikis yap" },
  landing: { heroTitle: "Alman Buerokrasisiyle Guvenle Basedebilme", heroSubtitle: "Vize, kayit ve Almanya'ya yerlesme icin adim adim rehberlik. 11 dilde mevcut.", getStarted: "Uecretsiz Basla", learnMore: "Daha Fazla Bilgi", featuresTitle: "Almanya'ya yerlesmeniz icin ihtiyaciniz olan her sey", feature1Title: "Vize Akis Motoru", feature1Desc: "Vize turuenueze goere kisisellestirilmis rehberler.", feature2Title: "Belge Kasasi", feature2Desc: "Tuem onemli belgelerinizi tek yerde takip edin.", feature3Title: "Tarih Hatirlaticilari", feature3Desc: "Vize yenileme veya randevulari asla kacirmayin.", feature4Title: "11 Dil", feature4Desc: "Tuerkce, Almanca, Ingilizce, Arapca ve daha fazlasinda mevcut.", howItWorksTitle: "Nasil Calisir", step1Title: "Hesap Olusturun", step1Desc: "Uecretsiz kaydolun ve vize turuenuezue soeyleyin.", step2Title: "Akisinizi Takip Edin", step2Desc: "Kisisellestirilmis bir kontrol listesi alin.", step3Title: "Ilerlemeyi Takip Edin", step3Desc: "Adimlari tamamlandi olarak isaretleyin.", ctaTitle: "Almanya'ya tasinmanizi kolaylastirmaya hazir misiniz?", ctaSubtitle: "Germany Guide kullanan binlerce goecmen ve oegrenciye katilin.", ctaButton: "Uecretsiz Hesap Olusturun", pricingTitle: "Basit, Seffaf Fiyatlandirma", pricingSubtitle: "Uecretsiz baslayin. Ihtiyaciniz oldugunda yueseltin.", freeTier: "Uecretsiz", premiumTier: "Premium", freePriceLabel: "Sonsuza kadar uecretsiz", freeFeature1: "3 aktif akisa kadar", freeFeature2: "10 belgeye kadar", freeFeature3: "Temel tarih takibi", freeFeature4: "Tuem 11 dil", premiumMonthly: "Aylik", premiumYearly: "Yillik" },
  auth: { loginTitle: "Tekrar Hos Geldiniz", loginSubtitle: "Hesabiniza giris yapin", registerTitle: "Hesap Olustur", registerSubtitle: "Almanya'daki yolculugunuza baslayin", email: "E-posta", password: "Sifre", confirmPassword: "Sifre Onayi", fullName: "Ad Soyad", signIn: "Giris Yap", signUp: "Kaydol", forgotPassword: "Sifremi unuttum?", noAccount: "Hesabiniz yok mu?", hasAccount: "Zaten hesabiniz var mi?", signUpLink: "Kaydol", signInLink: "Giris yap", orContinueWith: "Veya ile devam edin", google: "Google", passwordMismatch: "Sifreler eslesmedi", createOne: "Olusturun", registerDesc: "Uecretsiz hesabinizi olusturmak icin bilgilerinizi girin", passwordHint: "En az 6 karakter olmali", passwordTooShort: "Sifre en az 6 karakter olmali" },
  onboarding: { title: "Profilinizi Ayarlayin", subtitle: "Deneyiminizi kisisellestirmek icin bize kendinizden bahsedin", visaType: "Vize Tuerue", selectVisaType: "Vize turuenuezue secin", applicationType: "Basvuru Tuerue", firstApplication: "Ilk Basvuru", renewal: "Yenileme", city: "Sehir", selectCity: "Sehrinizi secin", zipCode: "Posta Kodu", enterZipCode: "Posta kodunuzu girin", visaExpiry: "Vize Bitis Tarihi", step1Title: "Vize Bilgileri", step1Desc: "Hangi tuer vize basvurusu yapiyorsunuz?", step2Title: "Konum", step2Desc: "Almanya'da nerede yasiyorsunuz?", step3Title: "Oenemli Tarihler", step3Desc: "Vizeniz ne zaman bitiyor?", complete: "Kurulumu Tamamla", skipForNow: "Simdilik atla", progress: "Adim {current} / {total}", visaPlaceholder: "Vize turuenue secin", cityPlaceholder: "Sehrinizi secin", zipPlaceholder: "oern. 10115", expiryHint: "Yenileme hatirlaticilari goendermemize yardimci olur", aboutYou: "Hakkinda", location: "Konum", completeSetup: "Kurulumu Tamamla", saveChanges: "Degisiklikleri Kaydet", welcome: "Germany Guide'a Hos Geldiniz" },
  dashboard: { title: "Kontrol Paneli", welcome: "Tekrar hos geldiniz", quickActions: "Hizli Islemler", recentFlows: "Son Akislar", upcomingDeadlines: "Yaklasan Tarihler", documentStatus: "Belge Durumu", noFlows: "Henuz aktif akis yok", noDeadlines: "Yaklasan tarih yok", startFlow: "Yeni Akis Baslatma", viewAll: "Tuemue Goeruentuele", yourProgress: "Ilerlemeniz", completedSteps: "Tamamlanan Adimlar", activeFlows: "Aktif Akislar", totalDocuments: "Toplam Belgeler", overview: "Genel Bakis", premiumBanner: "Premium'a Yuekselt", premiumBannerDesc: "Sinirsiz akislar, belgeler ve reklamsiz deneyim.", premiumBannerCta: "Simdi Yuekselt", tipCard: "Germany Guide'i Destekle", tipCardDesc: "Hizmeti suerduermeye yardimci olun.", tipCardCta: "Bahsis Birakin" },
  flows: { title: "Akislariniz", startNew: "Yeni Akis Baslatma", progress: "%{percent} tamamlandi", steps: "{count} adim", completed: "Tamamlandi", inProgress: "Devam Ediyor", notStarted: "Baslamadi", continueFlow: "Devam Et", viewDetails: "Detaylari Goeruentuele", stepOf: "Adim {current} / {total}", markDone: "Tamamlandi Olarak Isaretle", markUndone: "Tamamlanmadi Olarak Isaretle", notes: "Notlar", addNote: "Not ekle...", requiredDocs: "Gerekli Belgeler", usefulLinks: "Faydali Linkler", tips: "Ipuclari", optional: "Istege Bagli", flowCompleted: "Akis Tamamlandi!", allStepsDone: "Bu akistaki tuem adimlari tamamladiniz.", backToFlows: "Akislara Doenue", previousStep: "Oenceki", nextStep: "Sonraki", recommended: "Sizin Icin Oenerilen", myFlows: "Akislarim", recommendedForYou: "Sizin Icin Oenerilen", basedOnVisa: "Vize turuenueze goere", otherFlows: "Diger Akislar", yourNotes: "Notlariniz", undo: "Geri Al", markAsDone: "Tamamlandi Olarak Isaretle", completedSection: "Tamamlanan" },
  docs: { title: "Belgeler", addNew: "Belge Ekle", docType: "Belge Tuerue", docName: "Belge Adi", issueDate: "Verilis Tarihi", expiryDate: "Bitis Tarihi", status: "Durum", valid: "Gecerli", pending: "Beklemede", expired: "Suresi Dolmus", notUploaded: "Yueklenmedi", linkedFlow: "Bagli Akis", noDocuments: "Henuz belge eklenmedi", addFirst: "Takibe baslamak icin ilk belgenizi ekleyin", selectDocType: "Belge tuerue secin", enterDocName: "Belge adi girin", saveDocument: "Belgeyi Kaydet", deleteConfirm: "Bu belgeyi silmek istediginizden emin misiniz?", notesPlaceholder: "Not ekleyin...", documentVault: "Belge Kasasi", addNewDocument: "Yeni Belge Ekle", backToDocuments: "Belgelere Doenue", selectTypeAndName: "Tuer ve ad secin", linkToFlow: "Akisa Bagla", none: "Yok", issued: "Verildi", expires: "Bitiyor", expiringSoon: "Yakinda Bitiyor" },
  deadlines: { title: "Tarihler", addNew: "Tarih Ekle", dueDate: "Bitis Tarihi", reminder: "Hatirlatici", done: "Tamamlandi", pending: "Beklemede", overdue: "Gecikti", noDeadlines: "Tarih belirlenmedi", addFirst: "Takip icin bir tarih ekleyin", deadlineTitle: "Baslik", description: "Aciklama", setReminder: "Hatirlatici Ayarla", reminderDate: "Hatirlatici Tarihi", saveDeadline: "Tarihi Kaydet", markComplete: "Tamamlandi Isaretle", deleteConfirm: "Bu tarihi silmek istediginizden emin misiniz?", titlePlaceholder: "oern. Vize Yenileme", descPlaceholder: "Detay ekleyin...", titleDesc: "Baslik ve Aciklama", addNewDeadline: "Yeni Tarih Ekle", due: "Bitis", daysLeft: "guen kaldi", startReminding: "Hatirlatmayi Baslatma", noPending: "Bekleyen tarih yok", completedSection: "Tamamlanan Tarihler", titleAndDateRequired: "Baslik ve tarih gereklidir" },
  nav: { dashboard: "Kontrol Paneli", flows: "Akislar", documents: "Belgeler", deadlines: "Tarihler", settings: "Ayarlar", help: "Yardim", profile: "Profil", premium: "Premium", upgrade: "Yuekselt" },
  visa: { student_visa: "Oegrenci Vizesi", job_seeker_visa: "Is Arayan Vizesi", blue_card: "AB Mavi Kart", work_permit: "Calisma Izni", family_reunion: "Aile Birlesimi", freelance_visa: "Serbest Calisan Vizesi", permanent_residence: "Surekli Oturma Izni", other: "Diger" },
  premium: { title: "Premium'a Yuekselt", subtitle: "Tuem oezellikleri acin ve reklamlari kaldirin", monthly: "Aylik", yearly: "Yillik", monthlyPrice: "4,99", yearlyPrice: "39,99", perMonth: "/ay", perYear: "/yil", savePercent: "%33 Tasarruf", subscribe: "Simdi Abone Ol", currentPlan: "Mevcut Plan", managePlan: "Aboneligi Yoenet", cancelAnytime: "Istediginiz zaman iptal edin", feature1: "Sinirsiz akislar", feature2: "Sinirsiz belgeler", feature3: "Oencelikli hatirlaticilar", feature4: "Reklamsiz deneyim", feature5: "PDF disa aktarma", feature6: "Oencelikli destek", free: "Uecretsiz", premiumBadge: "Premium", upgradeNow: "Simdi Yuekselt", included: "Dahil", notIncluded: "Dahil degil", mostPopular: "En Populer", bestValue: "En Iyi Deger", successTitle: "Premium'a Hos Geldiniz!", successDesc: "Aboneliginiz simdi aktif.", goToDashboard: "Kontrol Paneline Git", billedMonthly: "Aylik faturalandirilir", billedYearly: "Yillik faturalandirilir" },
  affiliates: { title: "Oenerilen Hizmetler", subtitle: "Almanya'ya yerlesmenize yardimci guvenilir hizmetler", banking: "N26", insurance: "TK", mobile: "Fraenk", housing: "WG-Gesucht", visitSite: "Siteyi Ziyaret Et", sponsored: "Ortak", bankingDesc: "Uecretsiz dijital banka hesabi. Dakikalar icinde acin.", insuranceDesc: "Almanya'nin en iyi saglik sigortasi. Kolay online kayit.", mobileDesc: "Aylik 5 Euro'dan baslayan basit mobil planlar.", housingDesc: "Almanya genelinde ortak daireler ve evler bulun.", bankingTag: "Bankacilik", insuranceTag: "Sigorta", mobileTag: "Mobil", housingTag: "Konut" },
  support: { title: "Germany Guide'i Destekle", subtitle: "Bu hizmeti uecretsiz tutmamiza yardimci olun", tipAmount: "Bahsis Miktari", customAmount: "Oezel Miktar", sendTip: "Bahsis Goender", thankYouTitle: "Desteginiz icin tesekkuerler!", thankYouDesc: "Bahsisiniz Germany Guide'i gelistirmemize yardimci olur." },
  ads: { placeholder: "Reklam", hiddenForPremium: "Reklamlar premium kullanicilar icin gizlenir" },
  privacy: { title: "Gizlilik Politikasi" },
  terms: { title: "Kullanim Sartlari" },
  about: { title: "Germany Guide Hakkinda" },
} as unknown as Dictionary;
export default tr;