/* eslint-disable */
import type { Dictionary } from './en';

const uk = {
  common: { appName: 'Гід по Німеччині', loading: 'Завантаження...', save: 'Зберегти', cancel: 'Скасувати', delete: 'Видалити', edit: 'Редагувати', back: 'Назад', next: 'Далі', submit: 'Надіслати', yes: 'Так', no: 'Ні', or: 'або', error: 'Помилка', success: 'Успіх', close: 'Закрити', optional: 'Необов\'язково', required: 'Обов\'язково', search: 'Пошук', noResults: 'Нічого не знайдено', confirm: 'Підтвердити', welcome: 'Ласкаво просимо' },
  landing: { hero: 'Ваш повний гід по життю в Німеччині', subtitle: 'Орієнтуйтесь у бюрократії, керуйте документами та відстежуйте терміни — все в одному місці.', getStarted: 'Почати', login: 'Увійти', features: 'Функції', featureFlows: 'Покрокові процеси', featureFlowsDesc: 'Слідуйте керованим процесам для візових заявок, реєстрації та іншого.', featureDocs: 'Сховище документів', featureDocsDesc: 'Зберігайте та відстежуйте всі важливі документи з попередженнями про закінчення терміну.', featureDeadlines: 'Відстеження термінів', featureDeadlinesDesc: 'Більше ніколи не пропустіть зустріч або дату продовження.', featureI18n: 'Багатомовна підтримка', featureI18nDesc: 'Доступно 11 мовами, включаючи арабську, турецьку, українську та інші.', pricing: 'Ціни', pricingSubtitle: 'Виберіть план, який вам підходить', free: 'Безкоштовно', premium: 'Преміум', premiumPrice: '€4.99/місяць', premiumYearly: '€39.99/рік', saveYearly: 'Економія 33%', currentPlan: 'Поточний план', upgrade: 'Оновити зараз', freeTier1: 'До 3 активних процесів', freeTier2: 'До 10 документів', freeTier3: 'Базове відстеження термінів', freeTier4: 'Підтримка спільноти', premiumTier1: 'Необмежені процеси', premiumTier2: 'Необмежені документи', premiumTier3: 'Пріоритетна підтримка', premiumTier4: 'Без реклами', premiumTier5: 'Експорт документів у PDF', premiumTier6: 'Розширені нагадування', premiumTier7: 'Персоналізований чек-лист' },
  auth: { login: 'Увійти', register: 'Створити акаунт', email: 'Електронна пошта', password: 'Пароль', confirmPassword: 'Підтвердити пароль', forgotPassword: 'Забули пароль?', noAccount: 'Немає акаунту?', hasAccount: 'Вже є акаунт?', loginError: 'Невірна пошта або пароль', registerError: 'Реєстрація не вдалася. Спробуйте ще раз.', passwordMismatch: 'Паролі не збігаються', checkEmail: 'Перевірте пошту для підтвердження', fullName: 'Повне ім\'я', logout: 'Вийти' },
  onboarding: { title: 'Налаштуйте свій профіль', subtitle: 'Це допоможе нам персоналізувати ваш досвід', step1Title: 'Тип візи', step1Desc: 'Який тип візи у вас є або ви подаєте заявку?', step2Title: 'Деталі заявки', step2Desc: 'Розкажіть більше про вашу ситуацію', step3Title: 'Місцезнаходження', step3Desc: 'Де ви знаходитесь у Німеччині?', visaType: 'Тип візи', applicationType: 'Це ваша перша заявка чи продовження?', firstApplication: 'Перша заявка', renewal: 'Продовження', city: 'Місто', zipCode: 'Поштовий індекс', visaExpiry: 'Дата закінчення візи', complete: 'Завершити налаштування', step: 'Крок', of: 'з' },
  dashboard: { title: 'Панель керування', welcomeBack: 'З поверненням', yourFlows: 'Ваші процеси', yourDocuments: 'Ваші документи', upcomingDeadlines: 'Найближчі терміни', quickActions: 'Швидкі дії', startNewFlow: 'Почати новий процес', addDocument: 'Додати документ', viewAllFlows: 'Переглянути всі процеси', viewAllDocs: 'Переглянути всі документи', viewAllDeadlines: 'Переглянути всі терміни', noFlows: 'Ще немає активних процесів', noDocs: 'Ще немає документів', noDeadlines: 'Немає найближчих термінів', progress: 'Прогрес', dueIn: 'Через', days: 'днів', overdue: 'Прострочено', today: 'Сьогодні', premiumBanner: 'Оновити до Преміум', premiumBannerDesc: 'Необмежені процеси, без реклами та більше.', premiumBannerCta: 'Дізнатися більше' },
  flows: { title: 'Процеси', subtitle: 'Покрокові інструкції для вашого типу візи', startFlow: 'Почати процес', continueFlow: 'Продовжити', completed: 'Завершено', inProgress: 'В процесі', notStarted: 'Не розпочато', steps: 'Кроки', step: 'Крок', markDone: 'Позначити виконаним', markUndone: 'Позначити невиконаним', notes: 'Нотатки', addNote: 'Додати нотатку...', saveNote: 'Зберегти нотатку', requiredDocs: 'Необхідні документи', usefulLinks: 'Корисні посилання', tips: 'Поради', optional: 'Необов\'язковий крок', flowProgress: 'Прогрес процесу', noFlows: 'Немає процесів для вашого типу візи', backToFlows: 'Повернутися до процесів', limitReached: 'Досягнуто ліміт безкоштовного плану', limitReachedDesc: 'Оновіть до Преміум для необмежених процесів.' },
  docs: { title: 'Документи', subtitle: 'Відстежуйте всі важливі документи', addDocument: 'Додати документ', editDocument: 'Редагувати документ', docType: 'Тип документа', docName: 'Назва документа', issueDate: 'Дата видачі', expiryDate: 'Дата закінчення', status: 'Статус', notes: 'Нотатки', linkedFlow: 'Пов\'язаний процес', noDocuments: 'Документів ще не додано', valid: 'Дійсний', pending: 'Очікує', expired: 'Прострочений', notUploaded: 'Не завантажено', deleteConfirm: 'Ви впевнені, що хочете видалити цей документ?', limitReached: 'Досягнуто ліміт безкоштовного плану', limitReachedDesc: 'Оновіть до Преміум для необмежених документів.' },
  deadlines: { title: 'Терміни', subtitle: 'Ніколи не пропустіть важливу дату', addDeadline: 'Додати термін', editDeadline: 'Редагувати термін', deadlineTitle: 'Заголовок', description: 'Опис', dueDate: 'Дата виконання', remindAt: 'Нагадати', markDone: 'Позначити виконаним', markUndone: 'Позначити невиконаним', done: 'Виконано', upcoming: 'Найближчі', overdue: 'Прострочені', noDeadlines: 'Термінів не встановлено', deleteConfirm: 'Ви впевнені, що хочете видалити цей термін?' },
  nav: { dashboard: 'Панель', flows: 'Процеси', documents: 'Документи', deadlines: 'Терміни', settings: 'Налаштування', logout: 'Вийти', language: 'Мова', premium: 'Преміум', upgrade: 'Оновити' },
  visa: { student_visa: 'Студентська віза', job_seeker_visa: 'Віза для пошуку роботи', blue_card: 'Блакитна карта', work_permit: 'Дозвіл на роботу', family_reunion: 'Возз\'єднання сім\'ї', freelance_visa: 'Фріланс віза', permanent_residence: 'Постійне проживання', other: 'Інше' },
  premium: { title: 'Оновити до Преміум', subtitle: 'Розблокуйте всю потужність Гіду по Німеччині', monthly: 'Щомісяця', yearly: 'Щорічно', monthlyPrice: '€4.99/міс', yearlyPrice: '€39.99/рік', savePercent: 'Економія 33%', subscribe: 'Підписатися', manage: 'Керувати підпискою', cancel: 'Скасувати підписку', cancelConfirm: 'Ви впевнені, що хочете скасувати підписку?', active: 'Активна', cancelled: 'Скасована', expired: 'Закінчилась', renewsOn: 'Продовжується', expiresOn: 'Закінчується', feature1: 'Необмежені процеси та документи', feature2: 'Без реклами', feature3: 'Пріоритетна підтримка', feature4: 'Експорт PDF', feature5: 'Розширені нагадування (SMS та Email)', feature6: 'Персоналізовані чек-листи', thankYou: 'Дякуємо за підписку!', welcomePremium: 'Ласкаво просимо до Преміум.', paymentSuccess: 'Оплата успішна', paymentCancelled: 'Оплату скасовано', returnToDashboard: 'Повернутися на панель', processing: 'Обробка оплати...', error: 'Щось пішло не так. Спробуйте ще раз.' },
  affiliates: { recommended: 'Рекомендовані послуги', subtitle: 'Надійні партнери для вашого облаштування в Німеччині', banking: 'Банківські послуги', insurance: 'Медичне страхування', mobile: 'Мобільні тарифи', housing: 'Житло', learn: 'Дізнатися більше', disclaimer: 'Ми можемо отримувати комісію при реєстрації через наші посилання. Це не впливає на ціну.', openAccount: 'Відкрити рахунок', getQuote: 'Отримати пропозицію', viewPlans: 'Переглянути тарифи', findHousing: 'Знайти житло', bankingDesc: '\u0411\u0435\u0437\u043A\u043E\u0448\u0442\u043E\u0432\u043D\u0438\u0439 \u043D\u0456\u043C\u0435\u0446\u044C\u043A\u0438\u0439 \u0431\u0430\u043D\u043A\u0456\u0432\u0441\u044C\u043A\u0438\u0439 \u0440\u0430\u0445\u0443\u043D\u043E\u043A, \u0431\u0435\u0437 \u043F\u0430\u043F\u0435\u0440\u0456\u0432. \u0412\u0456\u0434\u043A\u0440\u0438\u0439\u0442\u0435 \u0437\u0430 8 \u0445\u0432\u0438\u043B\u0438\u043D.', insuranceDesc: '\u041D\u0430\u0439\u0431\u0456\u043B\u044C\u0448\u0435 \u0434\u0435\u0440\u0436\u0430\u0432\u043D\u0435 \u043C\u0435\u0434\u0441\u0442\u0440\u0430\u0445\u0443\u0432\u0430\u043D\u043D\u044F \u041D\u0456\u043C\u0435\u0447\u0447\u0438\u043D\u0438. \u041F\u0456\u0434\u0442\u0440\u0438\u043C\u043A\u0430 \u0430\u043D\u0433\u043B\u0456\u0439\u0441\u044C\u043A\u043E\u044E.', mobileDesc: '\u041F\u0440\u043E\u0441\u0442\u0456 \u043C\u043E\u0431\u0456\u043B\u044C\u043D\u0456 \u0442\u0430\u0440\u0438\u0444\u0438 \u0432\u0456\u0434 10 \u0454\u0432\u0440\u043E/\u043C\u0456\u0441. \u0411\u0435\u0437 \u043A\u043E\u043D\u0442\u0440\u0430\u043A\u0442\u0443.', housingDesc: '\u041F\u043B\u0430\u0442\u0444\u043E\u0440\u043C\u0430 \u21161 \u0432 \u041D\u0456\u043C\u0435\u0447\u0447\u0438\u043D\u0456 \u0434\u043B\u044F \u043F\u043E\u0448\u0443\u043A\u0443 \u0436\u0438\u0442\u043B\u0430.' },
  support: { tipTitle: 'Підтримайте цей проект', tipSubtitle: 'Допоможіть нам тримати цей гід безкоштовним та актуальним', tipAmount: 'Виберіть суму', tipCustom: 'Довільна сума', tipSend: 'Надіслати', tipThankYou: 'Дякуємо за підтримку!', tipOneTime: 'Одноразова підтримка' },
  ads: { sponsored: 'Спонсоровано', advertisement: 'Реклама' },
};

export default uk as unknown as Dictionary;