/* eslint-disable */
import type { Dictionary } from './en';

const zh = {
  common: { appName: '德国指南', loading: '加载中...', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', back: '返回', next: '下一步', submit: '提交', yes: '是', no: '否', or: '或', error: '错误', success: '成功', close: '关闭', optional: '可选', required: '必填', search: '搜索', noResults: '未找到结果', confirm: '确认', welcome: '欢迎' },
  landing: { hero: '您在德国生活的完整指南', subtitle: '导航官僚机构、管理文件、跟踪截止日期——一站式解决。', getStarted: '开始使用', login: '登录', features: '功能', featureFlows: '分步流程', featureFlowsDesc: '按照引导流程完成签证申请、城市注册等。', featureDocs: '文件保管库', featureDocsDesc: '存储和跟踪所有重要文件，附带到期提醒。', featureDeadlines: '截止日期追踪', featureDeadlinesDesc: '再也不会错过预约或续签日期。', featureI18n: '多语言支持', featureI18nDesc: '支持11种语言，包括阿拉伯语、土耳其语、乌克兰语等。', pricing: '定价', pricingSubtitle: '选择适合您的方案', free: '免费', premium: '高级版', premiumPrice: '€4.99/月', premiumYearly: '€39.99/年', saveYearly: '节省33%', currentPlan: '当前方案', upgrade: '立即升级', freeTier1: '最多3个活跃流程', freeTier2: '最多10个文件', freeTier3: '基本截止日期追踪', freeTier4: '社区支持', premiumTier1: '无限流程', premiumTier2: '无限文件', premiumTier3: '优先邮件支持', premiumTier4: '无广告体验', premiumTier5: '导出PDF文件', premiumTier6: '高级提醒功能', premiumTier7: '个性化清单' },
  auth: { login: '登录', register: '创建账户', email: '电子邮件', password: '密码', confirmPassword: '确认密码', forgotPassword: '忘记密码？', noAccount: '没有账户？', hasAccount: '已有账户？', loginError: '邮箱或密码无效', registerError: '注册失败，请重试。', passwordMismatch: '密码不匹配', checkEmail: '请检查邮箱确认账户', fullName: '全名', logout: '退出' },
  onboarding: { title: '设置您的个人资料', subtitle: '这有助于我们个性化您的体验', step1Title: '签证类型', step1Desc: '您持有或正在申请哪种签证？', step2Title: '申请详情', step2Desc: '告诉我们更多关于您的情况', step3Title: '位置', step3Desc: '您在德国的哪里？', visaType: '签证类型', applicationType: '这是首次申请还是续签？', firstApplication: '首次申请', renewal: '续签', city: '城市', zipCode: '邮编', visaExpiry: '签证到期日', complete: '完成设置', step: '步骤', of: '/' },
  dashboard: { title: '仪表板', welcomeBack: '欢迎回来', yourFlows: '您的流程', yourDocuments: '您的文件', upcomingDeadlines: '即将到来的截止日期', quickActions: '快速操作', startNewFlow: '开始新流程', addDocument: '添加文件', viewAllFlows: '查看所有流程', viewAllDocs: '查看所有文件', viewAllDeadlines: '查看所有截止日期', noFlows: '暂无活跃流程', noDocs: '暂无文件', noDeadlines: '暂无即将到来的截止日期', progress: '进度', dueIn: '还剩', days: '天', overdue: '已过期', today: '今天', premiumBanner: '升级到高级版', premiumBannerDesc: '无限流程、无广告体验等更多功能。', premiumBannerCta: '了解更多' },
  flows: { title: '流程', subtitle: '针对您签证类型的分步指南', startFlow: '开始', continueFlow: '继续', completed: '已完成', inProgress: '进行中', notStarted: '未开始', steps: '步骤', step: '步骤', markDone: '标记完成', markUndone: '标记未完成', notes: '笔记', addNote: '添加笔记...', saveNote: '保存笔记', requiredDocs: '所需文件', usefulLinks: '有用链接', tips: '提示', optional: '可选步骤', flowProgress: '流程进度', noFlows: '您的签证类型暂无可用流程', backToFlows: '返回流程', limitReached: '免费计划限制已达', limitReachedDesc: '升级到高级版享受无限流程。' },
  docs: { title: '文件', subtitle: '跟踪所有重要文件', addDocument: '添加文件', editDocument: '编辑文件', docType: '文件类型', docName: '文件名称', issueDate: '签发日期', expiryDate: '到期日期', status: '状态', notes: '备注', linkedFlow: '关联流程', noDocuments: '暂无文件', valid: '有效', pending: '待处理', expired: '已过期', notUploaded: '未上传', deleteConfirm: '确定要删除此文件吗？', limitReached: '免费计划限制已达', limitReachedDesc: '升级到高级版享受无限文件。' },
  deadlines: { title: '截止日期', subtitle: '不要错过任何重要日期', addDeadline: '添加截止日期', editDeadline: '编辑截止日期', deadlineTitle: '标题', description: '描述', dueDate: '截止日期', remindAt: '提醒时间', markDone: '标记完成', markUndone: '标记未完成', done: '已完成', upcoming: '即将到来', overdue: '已过期', noDeadlines: '暂无截止日期', deleteConfirm: '确定要删除此截止日期吗？' },
  nav: { dashboard: '仪表板', flows: '流程', documents: '文件', deadlines: '截止日期', settings: '设置', logout: '退出', language: '语言', premium: '高级版', upgrade: '升级' },
  visa: { student_visa: '学生签证', job_seeker_visa: '求职签证', blue_card: '蓝卡', work_permit: '工作许可', family_reunion: '家庭团聚', freelance_visa: '自由职业签证', permanent_residence: '永久居留', other: '其他' },
  premium: { title: '升级到高级版', subtitle: '解锁德国指南的全部功能', monthly: '月付', yearly: '年付', monthlyPrice: '€4.99/月', yearlyPrice: '€39.99/年', savePercent: '节省33%', subscribe: '立即订阅', manage: '管理订阅', cancel: '取消订阅', cancelConfirm: '确定要取消订阅吗？', active: '活跃', cancelled: '已取消', expired: '已过期', renewsOn: '续订日期', expiresOn: '到期日期', feature1: '无限流程和文件', feature2: '无广告体验', feature3: '优先支持', feature4: 'PDF导出', feature5: '高级提醒（短信和邮件）', feature6: '个性化清单', thankYou: '感谢订阅！', welcomePremium: '欢迎使用高级版。', paymentSuccess: '支付成功', paymentCancelled: '支付已取消', returnToDashboard: '返回仪表板', processing: '正在处理支付...', error: '出了点问题，请重试。' },
  affiliates: { recommended: '推荐服务', subtitle: '值得信赖的合作伙伴帮助您在德国安家', banking: '银行服务', insurance: '医疗保险', mobile: '手机套餐', housing: '住房', learn: '了解更多', disclaimer: '通过我们的链接注册时，我们可能会获得佣金。这不会影响您支付的价格。', openAccount: '开设账户', getQuote: '获取报价', viewPlans: '查看套餐', findHousing: '寻找住房', bankingDesc: '\u514D\u8D39\u5FB7\u56FD\u94F6\u884C\u8D26\u6237\uFF0C\u65E0\u9700\u7EB8\u8D28\u6587\u4EF6\u30028\u5206\u949F\u5373\u53EF\u5F00\u6237\u3002', insuranceDesc: '\u5FB7\u56FD\u6700\u5927\u7684\u516C\u5171\u533B\u7597\u4FDD\u9669\u3002\u63D0\u4F9B\u82F1\u8BED\u652F\u6301\u3002', mobileDesc: '\u7B80\u5355\u7684\u624B\u673A\u5957\u9910\uFF0C\u6BCF\u670810\u6B27\u5143\u8D77\u3002\u65E0\u9700\u5408\u540C\u3002', housingDesc: '\u5FB7\u56FD\u7B2C\u4E00\u7684\u5408\u79DF\u516C\u5BD3\u548C\u4F4F\u623F\u5E73\u53F0\u3002' },
  support: { tipTitle: '支持本项目', tipSubtitle: '帮助我们保持本指南免费和更新', tipAmount: '选择金额', tipCustom: '自定义金额', tipSend: '发送打赏', tipThankYou: '感谢您的支持！', tipOneTime: '一次性打赏' },
  ads: { sponsored: '赞助', advertisement: '广告' },
};

export default zh as unknown as Dictionary;