"use client";

import jsPDF from "jspdf";

interface FlowStep {
  title: string;
  description: string;
  step_order: number;
  is_done: boolean;
  user_notes: string;
  required_documents: string[];
  tips: string;
}

interface ExportData {
  flowTitle: string;
  progress: number;
  steps: FlowStep[];
  exportDate: string;
}

export function exportFlowToPDF(data: ExportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(20);
  doc.setTextColor(30, 64, 175);
  doc.text("Germany Guide", pageWidth / 2, y, { align: "center" });
  y += 12;

  doc.setFontSize(16);
  doc.setTextColor(17, 24, 39);
  doc.text(data.flowTitle, pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(107, 114, 128);
  doc.text(`Progress: ${data.progress}% | Exported: ${data.exportDate}`, pageWidth / 2, y, {
    align: "center",
  });
  y += 15;

  doc.setDrawColor(229, 231, 235);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  data.steps.forEach((step) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setTextColor(17, 24, 39);
    const checkbox = step.is_done ? "[x]" : "[ ]";
    doc.text(`${checkbox} Step ${step.step_order}: ${step.title}`, 20, y);
    y += 7;

    if (step.description) {
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      const descLines = doc.splitTextToSize(step.description, pageWidth - 50);
      doc.text(descLines, 28, y);
      y += descLines.length * 5 + 3;
    }

    if (step.tips) {
      doc.setFontSize(9);
      doc.setTextColor(59, 130, 246);
      const tipLines = doc.splitTextToSize(`Tip: ${step.tips}`, pageWidth - 50);
      doc.text(tipLines, 28, y);
      y += tipLines.length * 4 + 3;
    }

    if (step.required_documents && step.required_documents.length > 0) {
      doc.setFontSize(9);
      doc.setTextColor(107, 114, 128);
      doc.text("Required: " + step.required_documents.join(", "), 28, y);
      y += 5;
    }

    if (step.user_notes) {
      doc.setFontSize(9);
      doc.setTextColor(34, 197, 94);
      const noteLines = doc.splitTextToSize(`Notes: ${step.user_notes}`, pageWidth - 50);
      doc.text(noteLines, 28, y);
      y += noteLines.length * 4 + 3;
    }

    y += 5;
  });

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    "Generated by Germany Guide - https://my-germany-guide.vercel.app",
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  const filename = `germany-guide-${data.flowTitle.replace(/\s+/g, "-").toLowerCase()}.pdf`;
  doc.save(filename);
}

interface DocumentData {
  doc_type: string;
  doc_name: string;
  issue_date: string | null;
  expiry_date: string | null;
  status: string;
  notes: string | null;
}

export function exportDocumentsToPDF(documents: DocumentData[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(20);
  doc.setTextColor(30, 64, 175);
  doc.text("Germany Guide - Document Vault", pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text(`Exported: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: "center" });
  y += 15;

  doc.setDrawColor(229, 231, 235);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  documents.forEach((d) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setTextColor(17, 24, 39);
    doc.text(d.doc_name, 20, y);

    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.text(`Type: ${d.doc_type} | Status: ${d.status}`, 20, y + 5);

    const dates: string[] = [];
    if (d.issue_date) dates.push(`Issued: ${d.issue_date}`);
    if (d.expiry_date) dates.push(`Expires: ${d.expiry_date}`);
    if (dates.length > 0) {
      doc.text(dates.join(" | "), 20, y + 10);
      y += 5;
    }

    if (d.notes) {
      doc.setFontSize(9);
      doc.setTextColor(34, 197, 94);
      doc.text(`Notes: ${d.notes}`, 20, y + 10);
      y += 5;
    }

    y += 18;
  });

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    "Generated by Germany Guide - https://my-germany-guide.vercel.app",
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  doc.save("germany-guide-documents.pdf");
}